/*
-- Query: SELECT * FROM ATV.questions
LIMIT 0, 1000

-- Date: 2024-12-05 16:35
*/
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (1,'What is the first vaccine discovered?',4,'Smallpox','\'Smallpox\', \'Rabies\', \'Polio\', \'Tuberculosis\'','The world\'s first vaccine is the smallpox vaccine. Dr Edward Jenner created the world\'s first successful vaccine. He found out that people infected with cowpox were immune to smallpox, and used that information to create the smallpox vaccine.','2024-12-05 15:13:34','2024-12-05 15:30:03',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (2,'A vaccine requires a dosage of 0.5 mL per 10 kg of body weight. If a patient weighs 60 kg, how much vaccine should they receive?',NULL,'3mL','3mL, 6mL, 9mL, 12mL',NULL,'2024-12-05 15:16:19','2024-12-05 15:16:19',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (3,'Which virus is commonly associated with the flu?',9,'Influenza','\'HIV\', \'Influenza\', \'SARS-CoV-2\', \'Ebola\'','\"The influenza virus is associated with the flu, and it is a master of disguise! Each year, it changes just enough to evade our immune systems, which is why getting a yearly flu vaccine is recommended.\"','2024-12-05 15:16:19','2024-12-05 15:17:37',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (4,'Which vaccine was the first to be widely used for preventing smallpox?',14,'Smallpox vaccine','\'BCG\', \'MMR\', \'Smallpox vaccine\', \'Polio vaccine\'','\"The smallpox vaccine is used to prevent smallpox. The vaccine didn’t require injections when it was first administered! Early vaccines were given through a method called scarification, where a small scratch was made on the skin, and the vaccine was applied to the scratch. \"','2024-12-05 15:17:28','2024-12-05 15:17:28',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (5,'If a virus spreads to 3 new people every day, starting with 1 infected person, how many people will be infected after 7 days (assuming no one recovers)?',NULL,'22','\'21\', \'22\', \'24\', \'28\'',NULL,'2024-12-05 15:18:11','2024-12-05 15:18:11',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (6,'The BCG vaccine is used to protect against which disease?',7,'Tuberculosis','\'Tetanus\', \'Tuberculosis\', \'Hepatitis B\', \'Chickenpox\'','The BCG vaccine (Bacille Calmette-Guérin) protects against tuberculosis. It is over 100 years old and is still the only vaccine available for TB! It was developed in 1921 by French scientists Albert Calmette and Camille Guérin using a weakened strain of the TB bacteria. \"','2024-12-05 15:18:58','2024-12-05 15:18:58',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (7,'To achieve herd immunity, 80% of a population must be vaccinated. If the population is 500,000 people, how many need to be vaccinated?',NULL,'400,000','\'100,000\', \'200,000\', \'300,000\', \'400,000\'',NULL,'2024-12-05 15:19:36','2024-12-05 15:19:36',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (8,'A vaccine reduces infection rates by 70%. If 1,000 people are exposed to the virus, how many are likely to get infected after vaccination?',NULL,'300','\'700\', \'500\', \'300\', \'100\'',NULL,'2024-12-05 15:20:20','2024-12-05 15:20:20',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (9,'Which vaccine is given to prevent polio?',16,'IPV','\'Hepatitis B vaccine\', \'IPV\', \'BCG\', \'DTP\'','\"The IPV vaccine is given to prevent polio. When Dr. Jonas Salk developed the first successful polio vaccine in 1955, he famously chose not to patent it because he wanted the vaccine to be widely accessible and affordable, helping to stop polio without profit as a barrier. This decision has been estimated to have saved countless lives and is considered one of the biggest humanitarian gestures in medical history.\" ','2024-12-05 15:21:31','2024-12-05 15:23:50',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (10,'The MMR vaccine protects against which three diseases?',NULL,'Measles, Mumps, Rubella','\'Measles, Mumps, Rubella\', \'Measles, Malaria, Rabies\', \'Measles, Mumps, Rhinovirus\', \'Malaria, Mumps, Rabies\'','\"The MMR vaccine protects against Measles, Mumps and Rubella. A cool fact? Receiving the MMR vaccine doesn’t just protect against these three diseases! Studies suggest it may also boost the immune system in a way that helps protect against other infections.\"','2024-12-05 15:22:17','2024-12-05 15:22:17',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (11,'The probability of a virus mutating during replication is 1%. If the virus replicates 200 times, how many mutations are expected?',NULL,'7','\'7\', \'6\', \'3\', \'2\'',NULL,'2024-12-05 15:25:17','2024-12-05 15:25:17',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (12,'Which vaccine is given to prevent cervical cancer caused by HPV?',NULL,'HPV Vaccine','\'Flu vaccine\', \'HPV vaccine\', \'Rotavirus vaccine\', \'Chickenpox vaccine\'','\"The HPV vaccine not only protects against the human papillomavirus, which can cause cervical, throat, and other cancers, but it was also the first vaccine specifically designed to prevent a type of cancer. \"','2024-12-05 15:26:04','2024-12-05 15:27:24',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (13,'A vaccine generates 500 antibodies per hour in a person. How many antibodies will be generated after 8 hours?',NULL,'4000','\'3200\', \'4000\', \'4800\', \'5600\'',NULL,'2024-12-05 15:27:24','2024-12-05 15:27:24',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (14,'The Hepatitis B vaccine is recommended for which group?',NULL,'Infants at birth','\'Infants at birth\', \'Only adults\', \'Only the elderly\', \'Pregnant women only\'','\"The Hepatitis B vaccine is recommended for infants at birth. It is so effective that it was the first vaccine developed using recombinant DNA technology. It’s also one of the first vaccines to be included in infant vaccination schedules worldwide, offering protection against a virus that can cause chronic liver disease and liver cancer.\"','2024-12-05 15:27:24','2024-12-05 15:27:24',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (15,'A treatment reduces the viral load by 50% every hour. If the initial viral load is 1,000 particles, what will it be after 3 hours?',NULL,'125','\'500\', \'250\', \'125\', \'65\'',NULL,'2024-12-05 15:28:20','2024-12-05 15:28:20',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (16,'Which virus is the target of the rabies vaccine?',NULL,'Rabies virus','\'Ebola virus\', \'Influenza virus\', \'Rabies virus\', \'Zika virus\'','\"The rabies vaccine helps prevent rabies. The rabies virus attacks the nervous system, causing symptoms like aggression, confusion, and hydrophobia (fear of water), which is why the disease has long been associated with wild, rabid animals like dogs and bats. Despite being one of the deadliest diseases, rabies is entirely preventable through vaccination!\"','2024-12-05 15:28:20','2024-12-05 15:29:27',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (17,'The rotavirus vaccine is primarily given to prevent infections that affect which organ?',NULL,'Stomach','\'Lungs\', \'Liver\', \'Heart\', \'Stomach\'','\"The rotavirus is a virus that affects the stomach. Before the vaccine, rotavirus was responsible for millions of cases of severe diarrhea worldwide, leading to hundreds of thousands of hospitalizations each year. The vaccine has helped save lives and drastically reduce the burden on healthcare systems. In fact, it is estimated that since its introduction, the vaccine has prevented over 200,000 deaths globally!\"','2024-12-05 15:29:27','2024-12-05 15:30:07',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (18,'Which vaccine helps prevent tetanus, diphtheria, and pertussis?',NULL,'Tdap','\'Tdap\', \'HPV\', \'BCG\', \'MMR\'','\"The Tdap vaccine helps prevent tetanus, diphtheria, and pertussis. Tetanus, often called lockjaw, is caused by a toxin produced by the bacterium Clostridium tetani, which enters the body through cuts or puncture wounds. What\'s surprising is that the bacteria are found everywhere—in soil, dust, and even animal manure! \"','2024-12-05 15:31:33','2024-12-05 15:31:33',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (19,'A vaccine has an effectiveness of 90%. If 1,000 people are vaccinated, how many of them are effectively protected?',NULL,'900','\'100\', \'300\', \'500\', \'900\'',NULL,'2024-12-05 15:31:33','2024-12-05 15:31:33',NULL,NULL);
INSERT INTO `questions` (`id`,`question`,`agent_id`,`correct_answer`,`options`,`info`,`created_at`,`updated_at`,`created_by`,`updated_by`) VALUES (20,'Which vaccine was developed during the COVID-19 pandemic?',NULL,'Pfizer-BioNTech','\'Influenza vaccine\', \'Pfizer-BioNTech\', \'HPV vaccine\', \'Hepatitis B vaccine\'','\"The Pfizer-BioNTech vaccine was developed during the COVID-19 pandemic. Did you know that COVID-19 was the first pandemic in history to be officially recognized as a public health emergency of international concern by the World Health Organization (WHO) on January 30, 2020, before the virus even became widespread in many countries?!\"','2024-12-05 15:31:33','2024-12-05 15:31:33',NULL,NULL);
